sudo: false

cache:
  bundler: true

addons:
  postgresql: "9.4"

language: node_js
node_js:
  - 4.4.5

install:
  - rvm use 2.2.2 --install --binary --fuzzy
  - make install

before_script:
  - bundle exec rake db:create db:migrate

script:
  - bundle exec rake
  - make test

notifications:
  email: false
